server:
  port: 8081
spring:
  data:
    elasticsearch:
      repositories:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog_like?useSSL=false&serverTimezone=UTC
    username: root
    password: 111111
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
      timeout: 5000
      rabbitmq:
        host: 127.0.0.1
        port: 15672
        username: guest
        password: guest
    elasticsearch:
      rest:
        uris: 182.92.149.107:9200

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段


elasticsearch:
  host-and-port: 182.92.149.107:9200


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xinqi.bean # 别名扫描包
logging:
  level:
    root: info
    com.xinqi: debug
    org.elasticsearch: debug


management:
  health:
    elasticsearch:
      enabled: false